# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [0]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [0]:
print(np.__version__)
print(np.show_config())

1.17.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [0]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [0]:
python3 -c "import numpy;numpy.info(numpy.add)"

SyntaxError: ignored

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [0]:
s=np.zeros(10)
s[4]=1
print(s)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [0]:
s=np.arange(10,50)
print(s)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [0]:
s=np.arange(10,50)
s=s[::-1]
print(s)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [0]:
s=np.arange(9).reshape(3,3)
print(s)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [0]:
s=np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [0]:
s=np.eye(3)
print(s)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [0]:
s=np.random.random((3,3,3))
print(s)

[[[0.28095257 0.69736839 0.96963388]
  [0.47587539 0.17408506 0.78374341]
  [0.23482906 0.54643812 0.49838243]]

 [[0.67841843 0.57685466 0.93367952]
  [0.31782058 0.97728192 0.84357673]
  [0.70190169 0.65043443 0.66448365]]

 [[0.53983134 0.75097779 0.43214731]
  [0.03245577 0.4551502  0.39362408]
  [0.16370359 0.1058166  0.46346025]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [0]:
s=np.random.random((10,10))
min=s.min()
max=s.max()
print(min,max)

0.01637493822982261 0.9882382373421943


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [0]:
s=np.random.random(30)
m=s.mean()
print(m)

0.4775375556806047


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [0]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0

NameError: ignored

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [0]:
import numpy as np
s=np.ones((3,3))
s=np.pad(s, pad_width=1, mode='constant', constant_values=0)
print(s)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [0]:
import numpy as np
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan -np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [0]:
import numpy
s=np.diag(1+numpy.arange(4),k=-1)
print(s)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [0]:
s = np.zeros((8,8),dtype=int)
s[1::2,::2] = 1
s[::2,1::2] = 1
print(s)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [0]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [0]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [0]:
import numpy as np
s=np.random.random((5,5))
s=(s-np.mean(s))/(np.std(s))
print(s)

[[ 1.41354364  1.45298391  0.90266597  1.33106871  0.61006642]
 [ 0.79088737 -1.34121387  0.08375479 -0.64370115 -0.31782298]
 [-1.33250792 -1.69134821 -1.54754368 -0.85700157 -0.03642253]
 [-0.52805694 -0.49365415  0.82514126  1.11192128  0.34368195]
 [ 0.03383695 -0.72962081 -1.32245958  1.46728297  0.47451817]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [0]:
import numpy as np
s=np.ones((5,3))@np.ones((3,2))
print(s)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [0]:
s=np.arange(11)
s[(s>3)&(s<=8)]*= -1
print(s)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [0]:
print(sum(range(5),--1))
from numpy import *
print(sum(range(5),-1))

AxisError: ignored

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [0]:
z=np.arange(5)
print(1j*z)
print(z/1/2)


[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0.  0.5 1.  1.5 2. ]


1.z**z is legal and it is broadcasting    
2.2<<z>>2 is legal,it first operates left shift on z and then right shift   
3.z<-z,z>-z are invalid   
4.1j*z is valid and it multiplies the complex number 1j to each and every element of the array and gives the modified array   
5.z/1/1 divides the array two times and results the modified array  
6.z<z>z is invalid 





#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

<built-in function array>


1.np.array(0) / np.array(0) returns nan   
2.np.array(0)//np.array(0) returns 0   


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [0]:
s1=np.random.randint(0,10,10)
s2=np.random.randint(0,10,10)
print(np.intersect1d(s1,s2))

[3 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [0]:
warnings.filterwarnings('ignore')

Warnings can be ignores by using the warnings module by adding the following line into our code
warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

the statement gives false because
np.emath.sqrt(-1) returns 1j whereas np.sqrt(-1) returns nan  
Hence the expression results false.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [0]:
import numpy as np
from datetime import datetime
yesterday=np.datetime64('today','D') - np.timedelta64(1,'D')
print("Yesterday:",yesterday)
today=np.datetime64('today','D')
print("Today:",today)
tomorrow=np.datetime64('today','D')+np.timedelta64(1,'D')
print("Tomorrow:",tomorrow)

Yesterday: 2019-12-26
Today: 2019-12-27
Tomorrow: 2019-12-28


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [0]:
import numpy as np
print("July,2016")
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

July,2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [0]:
p=np.ones(5)*1
q=np.ones(5)*5
r=np.ones(5)*10
np.add(p,q,out=q)
np.divide(p,2,out=p)
np.negative(p,out=p)
np.multiply(p,q,out=p)
print(p)

[-3. -3. -3. -3. -3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [0]:
s=np.random.uniform(0,10,10)
print(s-s%1)
print(np.floor(s))
print(np.ceil(s)-1)
print(s.astype(int))
print(np.trunc(s))

[5. 9. 8. 4. 7. 5. 8. 1. 8. 5.]
[5. 9. 8. 4. 7. 5. 8. 1. 8. 5.]
[5. 9. 8. 4. 7. 5. 8. 1. 8. 5.]
[5 9 8 4 7 5 8 1 8 5]
[5. 9. 8. 4. 7. 5. 8. 1. 8. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [0]:
p=np.zeros((5,5))
p+=np.arange(5)
print(p)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [0]:
def generate():
  for y in range(10):
    yield y
s=np.fromiter(generate(),dtype=int,count=-1)
print(s)  

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [0]:
s=np.linspace(0,1,12,endpoint=True)[1:-1]
print(s)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [0]:
s=np.random.random(10)
s.sort()
print(s)

[0.03279575 0.11551284 0.11627957 0.17704608 0.18985325 0.27183916
 0.83006972 0.83499495 0.89772406 0.98080889]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [0]:
z=np.arange(10)
z=np.add.reduce(z)
print(z)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [0]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
print(np.array_equal(a,b))
print(np.allclose(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [0]:
s=np.zeros(10)
s.flags.writeable=False
print(s)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [0]:
s=np.arange(10)
print(s)
p,q=s[:,0],s[:,1]


[0 1 2 3 4 5 6 7 8 9]


IndexError: ignored

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)